version: '3.8'

services:
  selling_my_car_db:
    image: mariadb
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=268435456
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - ${PWD}/database:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - ${DB_PORT}:${MYSQL_PORT}

  selling_my_car_api:
    image: ${DOCKER_REGISTRY_B}:main
    restart: always
    ports:
      - ${API_PORT}:8080
    volumes: 
      - ${PWD}/api:/home
    depends_on:
      - selling_my_car_db

  selling_my_car_web:
    image: ${DOCKER_REGISTRY_F}:main
    restart: always
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - selling_my_car_api